### ISSUE TITLE
exists instanceof != null und so... fritte ist kein Parselmund

### ISSUE THREAD

**Issue by derbytau** [Frittenfett/streamlabs_subs#1]
```
if not user in strikes:
    strikes[user] = 0

```

einfach davor schreiben

https://github.com/Frittenfett/streamlabs_subs/blob/d1ba18a1ee9387cd7207dd1574713a716657e487/subs_StreamlabsSystem.py#L214

**Comment by Frittenfett** [comment]
AAAAAAAAaaaaaaaaaaaaA
